# Unless required by applicable law or agreed to writing, software distributed
# under the License is distributed on a "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

version: gae
runtime: go
api_version: go1

handlers:
- url: /generate
  script: _go_app

- url: /
  static_files: static/home.html
  upload: static/home.html

- url: /
  static_dir: static
